[package]
name = "bio-mon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
libbpf-rs = "0.25.0"
libc = "0.2.154"
ctrlc = "3.1"
lazy_static = "1.5.0"
plain = "0.2.3"

[build-dependencies]
anyhow = "1.0"
libbpf-cargo = "0.25.0"
